services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=07032006
      - POSTGRES_DB=trebt
    command: postgres -c max_connections=200 -c listen_addresses='*'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
