// This file was generated by Prisma, and assumes you have installed the following:
// pnpm install --save-dev prisma dotenv
import 'dotenv/config';

import { join } from 'path';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: join('prisma', 'schema'),
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: "postgres://postgres:07032006@localhost:5432/template1?sslmode=disable",
  },
});
